### ISSUE TITLE
.fql files are in fact js files

### ISSUE THREAD

**Issue by zvictor** [zvictor/faugra#4]
FQL files should not use `q.` before every command. That's only needed in JS files running FQL commands and, still, that's how we are defining our .fql files in faugra:

https://github.com/zvictor/faugra/blob/2a52cb1590df1aca3c64f86ebe0d39d183c17bf9/examples/basic/sayHello.fql#L1-L3

The reason is that I couldn't  figure out how to call [CreateFunction](https://docs.fauna.com/fauna/current/api/fql/functions/createfunction) passing the raw fql commands, so I had to make use of the terribly unsafe `eval`:

https://github.com/zvictor/faugra/blob/2a52cb1590df1aca3c64f86ebe0d39d183c17bf9/commands/define-functions.js#L38-L42

I with I could do something like `CreateFunction({ body: fs.readFileSync(body) })` instead, but CreateFunction doesn' accept strings as `body`.
Is there any better way?

**Comment by lregnier** [comment]
With the the shell, it is possible to execute queries from a file:

https://github.com/fauna/fauna-shell#executing-queries-from-a-file

The shell is built with JavaScript, so maybe you can reuse that functionality directly from there or embedded in your code? :)

**Comment by zvictor** [comment]
that will probably work! I will give it a try when I put some more time into faugra again :) Thanks!
